### PR TITLE
Always restart dynos after deploy

### LINKED ISSUE #82: Does not always restart Hasura server
At the end of the deploy we have this logic:

```typescript
if (freshMainApp) {
  // seed datbase
  // scale up main app
  // scale up hasura app
} else if (databaseHasChanged) {
  // restart main app
  // restart hasura app
}
```

But this assumes that having a "fresh main app" (i.e. the app was just created in Heroku as part of this release) then the Hasura instance does not exist.
This is not necessarily always true.

It seems to be possible for the Hasura instance to already scale itself up (not sure why/how) -- but we should check the current server status and decide whether to scale up or restart the dyno.

### PR DESCRIPTION
**Pull request by stayradiated**
Closes #82

Add logic to check what dynos are currently running and decide whether to boot them (scale=1) or restart them.

This still lets production to run at scale of >=1, because it will already be running -- so it always go with the restart option.

- Also updates all dependencies to their latest versions.

## Testing

**Unit Tests**

There are unit tests for the `bootOrRestartProcess` function included in the PR.

**Manual Tests**

It is quite easy to manually test this, it just takes a while while waiting for the actions to run.

I've already manually tested this quite thoroughly on this PR: https://github.com/Runn-Fast/runn/pull/6361

The process I used is:

1. Create a branch from `runn-fast/runn#development` that uses this version of the github action (currently `1.17.0-beta.1`
2. Create a PR for that branch so that it deploys the apps to Heroku.
3. Check the action logs (click "Details" in the PR, specifically "App" job)
image
4. Open up the "Deploy to Heroku" step and look at the last few commands.
image
Note the `/usr/local/bin/heroku ps:scale web=1 worker=1 --app runn-pr-6361-app` line, this means that the process was "booted" (scaled from to 0).
5. Check that the Ap and Hasura servers are running
6. Try re-running the action, this time it should restart the service (`/usr/local/bin/heroku ps:restart web --app runn-pr-6361-app`)
image

### CODE REVIEW

**Comment by ro-savage** [comment]
@stayradiated - This will restart the hasura dyno after every deploy?
So for example, it would restart the production hasura dyno everytime? (Previously we only did it on db:migrate?)

**Comment by stayradiated** [comment]
> @stayradiated - This will restart the hasura dyno after every deploy?
> So for example, it would restart the production hasura dyno everytime? (Previously we only did it on db:migrate?)

The Hasura dyno would be restarted on each deploy, as Hasura does a restart when you change an env var. It just does a second restart after the DB and App server have been setup.

It's not as efficient as it used to be, but I don't think it should be alright to have an extra restart, even if it doesn't technically need it.

I could bring back the "only restart Hasura if there was a DB migrate" code if you want.

**Comment by ro-savage** [comment]
I think it's better to be safe at the moment. They'll be a small amount of downtime regardless. Just wanted to check.

**Review by ro-savage — APPROVED** [review]
Tested and works as expected. Thanks George!

**Pull request merged**
